### ISSUE TITLE
Wrong domain name in readme?

### ISSUE THREAD

**Issue by timoteostewart** [boppreh/hello_tls#1]
In the readme, below the command line example of `python -m hello_tls google.com` the output looks like it's for boppreh.com, not google.com.

**Comment by boppreh** [comment]
Good catch! I switched because Google's output was significantly longer. It's fixed now, thanks for the hint.

**Comment by boppreh** [comment]
Good catch! I switched because Google's output was significantly longer. It's fixed now, thanks for the hint.

**Comment by timoteostewart** [comment]
Happy to help! Cool program.
