### ISSUE TITLE
not executable?

### ISSUE THREAD

**Issue by clane2812** [boppreh/hello_tls#8]
Hello - perhaps i missed something, but i can´t find a hello_tls.py file in your repo? Was not able to execute with the documented steps in readme.md:

git clone https://github.com/boppreh/hello_tls.git
cd hello_tls
python hello_tls.py boppreh.com

**Comment by boppreh** [comment]
If you're just trying to execute it, I suggest installing via pip:

```
pip install hello_tls
```

If you want to run the cloned repo, try

```
git clone https://github.com/boppreh/hello_tls.git
cd hello_tls/src
python -m hello_tls boppreh.com --no-certs
```

The ` --no-certs`  option is required if you don't have PyOpenssl installed.

Note that there is no ` hello_tls.py` file, but that's just one way of executing Python. [Another way, used in this project](https://docs.python.org/3/library/__main__.html#main-py-in-python-packages), is to have a directory with [`__init__.py`](https://github.com/boppreh/hello_tls/blob/main/src/hello_tls/__init__.py) and [`__main__.py`](https://github.com/boppreh/hello_tls/blob/main/src/hello_tls/__main__.py) files.

**Comment by clane2812** [comment]
thanks - worked :) - perhaps it should be changed in the readme?

**Comment by boppreh** [comment]
Oh, I missed it that your code came from the README. Yes, definitely my fault, I've updated the README. Thanks for the tip.
